In [24]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
df = pd.read_csv("../../dataset/news_preprocess.csv")
df

,Judul,Content,processed,processed_text
0,Jokowi Kenakan Pakaian Adat Betawi di Sidang T...,"JAKARTA, KOMPAS.com - Presiden Joko Widodo me...","['jakarta', 'kompascom', 'presiden', 'joko', '...",jakarta kompascom presiden joko widodo pakai b...
1,Amnesty International Beberkan 6 Indikator Kri...,"TEMPO.CO, Jakarta - Amnesty International Indo...","['tempoco', 'jakarta', 'amnesty', 'internation...",tempoco jakarta amnesty international indonesi...
2,"Jelang Long Weekend, Stasiun Kereta Cepat Hali...","Stasiun kereta cepat Whoosh di Halim, Jakarta ...","['stasiun', 'kereta', 'cepat', 'whoosh', 'hali...",stasiun kereta cepat whoosh halim jakarta timu...
3,KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa...,"JAKARTA, KOMPAS.com - Komisi Pemilihan Umum (...","['jakarta', 'kompascom', 'komisi', 'pilih', 'u...",jakarta kompascom komisi pilih umum kpu ri pas...
4,Kemenag Luncurkan Gerakan Senam Haji Jaga Keta...,"TEMPO.CO, Jakarta - Kementerian Agama atau Kem...","['tempoco', 'jakarta', 'menteri', 'agama', 'ke...",tempoco jakarta menteri agama kemenag luncur s...
5,Bawaslu Minta Jajarannya Siapkan LHP Hadapi Gu...,"TEMPO.CO, Jakarta - Anggota Badan Pengawas Pem...","['tempoco', 'jakarta', 'anggota', 'badan', 'aw...",tempoco jakarta anggota badan awas pilih umum ...
6,Polisi Ungkap Aktivitas Depoy Bandar Narkoba S...,Polisi menyebutkan pria inisial DK alias Depoy...,"['polisi', 'sebut', 'pria', 'inisial', 'dk', '...",polisi sebut pria inisial dk alias depoy temu ...
7,"Truk Mogok di Perlintasan Kereta Serpong, 17 P...",Satu unit truk Fuso mogok di pelintasan kereta...,"['satu', 'unit', 'truk', 'fuso', 'mogok', 'lin...",satu unit truk fuso mogok lintas kereta rel li...
8,Jalan Buntu Anies Baswedan di Pilkada Jakarta ...,"TEMPO.CO, Jakarta - Bendahara Umum PDIP, Olly ...","['tempoco', 'jakarta', 'bendahara', 'umum', 'p...",tempoco jakarta bendahara umum pdip olly dondo...
9,Warga Sebut Ada Benda Serupa Jimat pada Mayat ...,"TANGERANG SELATAN, KOMPAS.com - Seutas tali b...","['tangerang', 'selatan', 'kompascom', 'utas', ...",tangerang selatan kompascom utas tali warna hi...

In [ ]:
tfidf = TfidfVectorizer() 
tfidf_matrix = tfidf.fit_transform(df['processed_text'])

In [27]:
feature_names = tfidf.get_feature_names_out()

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), index=df['Judul'], columns=feature_names)

tfidf_df.to_csv('../../dataset/tfidf_matrix.csv')

In [28]:
df = pd.read_csv("tfidf_matrix.csv")
df

,Judul,aa,abang,abdurrahman,abetnego,acu,ada,adapun,adat,adik,...,wawan,whoosh,wib,widodo,wienanto,wigata,yakin,yaqut,yudha,zaman
0,Jokowi Kenakan Pakaian Adat Betawi di Sidang T...,0.000000,0.000000,0.000000,0.206981,0.00000,0.000000,0.051745,0.310471,0.00000,...,0.000000,0.000000,0.000000,0.043988,0.000000,0.000000,0.000000,0.000000,0.000000,0.043988
1,Amnesty International Beberkan 6 Indikator Kri...,0.000000,0.000000,0.000000,0.000000,0.02973,0.000000,0.000000,0.000000,0.02973,...,0.000000,0.000000,0.000000,0.025273,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,"Jelang Long Weekend, Stasiun Kereta Cepat Hali...",0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.141076,0.299820,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa...,0.000000,0.000000,0.000000,0.000000,0.00000,0.054486,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Kemenag Luncurkan Gerakan Senam Haji Jaga Keta...,0.000000,0.000000,0.000000,0.000000,0.00000,0.065528,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.029369,0.000000,0.000000
5,Bawaslu Minta Jajarannya Siapkan LHP Hadapi Gu...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Polisi Ungkap Aktivitas Depoy Bandar Narkoba S...,0.384059,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,"Truk Mogok di Perlintasan Kereta Serpong, 17 P...",0.000000,0.365149,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Jalan Buntu Anies Baswedan di Pilkada Jakarta ...,0.000000,0.000000,0.028533,0.000000,0.00000,0.042441,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.028533,0.000000,0.028533,0.000000,0.028533,0.000000
9,Warga Sebut Ada Benda Serupa Jimat pada Mayat ...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,...,0.206005,0.000000,0.035025,0.000000,0.000000,0.041201,0.000000,0.000000,0.000000,0.035025

In [29]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [30]:

indices = pd.Series(df.index, index=df['Judul']).drop_duplicates()

In [31]:
cosine_df = pd.DataFrame(cosine_sim, index=df['Judul'], columns=df['Judul'])

cosine_df.to_csv('../../dataset/cosine_similarity.csv')

In [32]:
df = pd.read_csv("../../dataset/cosine_similarity.csv")
df

,Judul,"Jokowi Kenakan Pakaian Adat Betawi di Sidang Tahunan Terakhirnya, Simbol Terima Kasih untuk Jakarta",Amnesty International Beberkan 6 Indikator Krisis Demokrasi di Indonesia,"Jelang Long Weekend, Stasiun Kereta Cepat Halim Ramai Penumpang Malam Ini","KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa ""Nyoblos"", Begini Mekanismenya",Kemenag Luncurkan Gerakan Senam Haji Jaga Ketahanan Fisik Jemaah,Bawaslu Minta Jajarannya Siapkan LHP Hadapi Gugatan Sengketa Pemilu 2024,Polisi Ungkap Aktivitas Depoy Bandar Narkoba Sebelum Tewas dalam Toren,"Truk Mogok di Perlintasan Kereta Serpong, 17 Perjalanan KRL Terganggu","Jalan Buntu Anies Baswedan di Pilkada Jakarta 2024, Berikut Lika-liku Perjalanannya",Warga Sebut Ada Benda Serupa Jimat pada Mayat Dalam Sarung di Pamulang
0,Jokowi Kenakan Pakaian Adat Betawi di Sidang T...,1.000000,0.074662,0.010798,0.040000,0.035908,0.027452,0.078661,0.003084,0.054554,0.031739
1,Amnesty International Beberkan 6 Indikator Kri...,0.074662,1.000000,0.021003,0.065266,0.056374,0.083537,0.037783,0.007655,0.098452,0.049305
2,"Jelang Long Weekend, Stasiun Kereta Cepat Hali...",0.010798,0.021003,1.000000,0.027070,0.016100,0.016421,0.023370,0.020625,0.020615,0.047377
3,KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa...,0.040000,0.065266,0.027070,1.000000,0.030169,0.138789,0.015901,0.001523,0.059171,0.040905
4,Kemenag Luncurkan Gerakan Senam Haji Jaga Keta...,0.035908,0.056374,0.016100,0.030169,1.000000,0.029418,0.022087,0.028096,0.024959,0.023049
5,Bawaslu Minta Jajarannya Siapkan LHP Hadapi Gu...,0.027452,0.083537,0.016421,0.138789,0.029418,1.000000,0.030392,0.002746,0.055834,0.043432
6,Polisi Ungkap Aktivitas Depoy Bandar Narkoba S...,0.078661,0.037783,0.023370,0.015901,0.022087,0.030392,1.000000,0.003697,0.031881,0.098075
7,"Truk Mogok di Perlintasan Kereta Serpong, 17 P...",0.003084,0.007655,0.020625,0.001523,0.028096,0.002746,0.003697,1.000000,0.005035,0.014603
8,Jalan Buntu Anies Baswedan di Pilkada Jakarta ...,0.054554,0.098452,0.020615,0.059171,0.024959,0.055834,0.031881,0.005035,1.000000,0.043318
9,Warga Sebut Ada Benda Serupa Jimat pada Mayat ...,0.031739,0.049305,0.047377,0.040905,0.023049,0.043432,0.098075,0.014603,0.043318,1.000000