In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../../dataset/news_preprocess.csv")
df = df_selected = df[['Judul', 'Content']]
df

,Judul,Content
0,jokowi kena pakai adat betawi sidang tahun akh...,jakarta kompascom presiden joko widodo pakai b...
1,amnesty international kan indikator krisis dem...,tempoco jakarta amnesty international indonesi...
2,jelang long weekend stasiun kereta cepat halim...,stasiun kereta cepat whoosh halim jakarta timu...
3,kpu tegas pilih tak daftar dpt nyoblos begini ...,jakarta kompascom komisi pilih umum kpu pasti ...
4,kemenag luncur gera senam haji jaga tahan fisi...,tempoco jakarta menteri agama kemenag luncur s...
...,...,...
95,program prioritas kemendikbud guru guru gerak ...,tempoco riau bijak merdeka ajar episode jumlah...
96,cerita korban tipu visa haji ilegal panas ding...,mek kompascom lukman bukan nama benar orang gu...
97,gerindra sebut reshuffle menkumham sinkronisas...,jakarta kompascom ketua hari partai gerindra s...
98,lawrence wong lantik jadi singapura,lawrence wong lantik perdana menteri singapura...
99,kpu jakarta gelar rapat pleno agustus bahas st...,kpu dki jakarta bakal gelar rapat pleno agustu...

In [4]:
from collections import Counter

def compute_tf(text):
    words = text.split()  # pisahkan kata
    freq = Counter(words)  # hitung jumlah tiap kata

    # tentukan max frequency
    if len(freq) == 0:
        max_freq = 1
    else:
        max_freq = max(freq.values())

    tf = {}

    # hitung TF
    for word in freq:
        count = freq[word]
        tf[word] = count / max_freq

    return tf

In [5]:
df["tf"] = df["Content"].apply(compute_tf)
df

,Judul,Content,tf
0,jokowi kena pakai adat betawi sidang tahun akh...,jakarta kompascom presiden joko widodo pakai b...,"{'jakarta': 0.5, 'kompascom': 0.125, 'presiden..."
1,amnesty international kan indikator krisis dem...,tempoco jakarta amnesty international indonesi...,"{'tempoco': 0.06666666666666667, 'jakarta': 0...."
2,jelang long weekend stasiun kereta cepat halim...,stasiun kereta cepat whoosh halim jakarta timu...,"{'stasiun': 1.0, 'kereta': 0.8, 'cepat': 0.6, ..."
3,kpu tegas pilih tak daftar dpt nyoblos begini ...,jakarta kompascom komisi pilih umum kpu pasti ...,"{'jakarta': 0.07692307692307693, 'kompascom': ..."
4,kemenag luncur gera senam haji jaga tahan fisi...,tempoco jakarta menteri agama kemenag luncur s...,"{'tempoco': 0.04, 'jakarta': 0.08, 'menteri': ..."
...,...,...,...
95,program prioritas kemendikbud guru guru gerak ...,tempoco riau bijak merdeka ajar episode jumlah...,"{'tempoco': 0.0625, 'riau': 0.125, 'bijak': 0...."
96,cerita korban tipu visa haji ilegal panas ding...,mek kompascom lukman bukan nama benar orang gu...,"{'mek': 0.42857142857142855, 'kompascom': 0.14..."
97,gerindra sebut reshuffle menkumham sinkronisas...,jakarta kompascom ketua hari partai gerindra s...,"{'jakarta': 0.6, 'kompascom': 0.2, 'ketua': 0...."
98,lawrence wong lantik jadi singapura,lawrence wong lantik perdana menteri singapura...,"{'lawrence': 0.14285714285714285, 'wong': 1.0,..."
99,kpu jakarta gelar rapat pleno agustus bahas st...,kpu dki jakarta bakal gelar rapat pleno agustu...,"{'kpu': 0.8, 'dki': 0.6666666666666666, 'jakar..."

In [6]:
from math import log

def compute_idf(df, column):
    N = len(df)  # jumlah dokumen
    word_doc_count = {}

    # hitung jumlah dokumen yang mengandung tiap kata
    for text in df[column]:
        words = text.split()
        unique_words = set(words)

        for word in unique_words:
            if word in word_doc_count:
                word_doc_count[word] = word_doc_count[word] + 1
            else:
                word_doc_count[word] = 1

    # hitung IDF
    idf = {}
    for word in word_doc_count:
        ni = word_doc_count[word]
        idf[word] = log(N / ni)

    return idf

In [8]:
idf = compute_idf(df, 'Content')
idf

{'baju': 2.995732273553991,
 'ujung': 3.506557897319982,
 'tangguh': 4.605170185988092,
 'sendiri': 1.8971199848858813,
 'luhur': 3.912023005428146,
 'pindah': 2.8134107167600364,
 'indonesia': 0.9675840262617057,
 'cermin': 3.506557897319982,
 'segera': 2.659260036932778,
 'kuat': 1.7719568419318754,
 'kasih': 2.120263536200091,
 'bangsa': 2.120263536200091,
 'kali': 2.0402208285265546,
 'resmi': 1.5606477482646683,
 'zaman': 3.912023005428146,
 'presiden': 1.0216512475319812,
 'bangsawan': 4.605170185988092,
 'representasi': 4.605170185988092,
 'hadap': 1.9661128563728327,
 'tambah': 1.6607312068216509,
 'lama': 1.07880966137193,
 'kena': 1.5606477482646683,
 'negeri': 2.0402208285265546,
 'kompascom': 1.6607312068216509,
 'abetnego': 4.605170185988092,
 'balik': 3.2188758248682006,
 'adapun': 1.6607312068216509,
 'gigih': 3.912023005428146,
 'suku': 3.912023005428146,
 'peci': 4.605170185988092,
 'berani': 2.995732273553991,
 'kata': 0.06187540371808745,
 'kota': 1.6607312068216509,
 'ksp': 4.605170185988092,
 'bangun': 1.6607312068216509,
 'motif': 3.2188758248682006,
 'jumat': 1.8325814637483102,
 'makna': 3.912023005428146,
 'staf': 3.2188758248682006,
 'bijaksana': 4.605170185988092,
 'sebut': 0.3424903089467759,
 'lengkap': 2.207274913189721,
 'betawi': 3.506557897319982,
 'deputi': 3.2188758248682006,
 'kalimantan': 3.506557897319982,
 'dpr': 1.5606477482646683,
 'sidang': 2.120263536200091,
 'tegas': 1.3862943611198906,
 'filosofis': 4.605170185988092,
 'serong': 4.605170185988092,
 'ibu': 2.659260036932778,
 'sopan': 4.605170185988092,
 'ungkap': 1.2378743560016172,
 'hadir': 1.6607312068216509,
 'tarigan': 4.605170185988092,
 'merdeka': 2.5257286443082556,
 'maju': 1.9661128563728327,
 'sejak': 1.7147984280919266,
 'jadi': 0.18632957819149354,
 'jakarta': 0.3011050927839216,
 'kompleks': 2.207274913189721,
 'adat': 3.912023005428146,
 'akulturasi': 4.605170185988092,
 'bagai': 1.7147984280919266,
 'tahun': 0.8915981192837835,
 'nusantara': 2.995732273553991,
 'agama': 2.5257286443082556,
 'punya': 2.120263536200091,
 'hitam': 2.995732273553991,
 'wajah': 3.2188758248682006,
 'widodo': 1.7719568419318754,
 'jauh': 1.8971199848858813,
 'nilainilai': 4.605170185988092,
 'dpd': 2.407945608651872,
 'senayan': 2.5257286443082556,
 'sangat': 1.6094379124341003,
 'hormat': 2.407945608651872,
 'alas': 2.0402208285265546,
 'warna': 2.995732273553991,
 'tunjuk': 2.0402208285265546,
 'tahan': 2.0402208285265546,
 'kepala': 1.4271163556401458,
 'asal': 2.207274913189721,
 'terang': 1.5606477482646683,
 'taat': 4.605170185988092,
 'budaya': 2.407945608651872,
 'jokowi': 1.3862943611198906,
 'sama': 0.9416085398584451,
 'lintas': 2.0402208285265546,
 'terima': 1.1394342831883648,
 'timur': 1.9661128563728327,
 'perlemen': 4.605170185988092,
 'mpr': 2.995732273553991,
 'simbol': 3.506557897319982,
 'pakai': 2.407945608651872,
 'joko': 1.7147984280919266,
 'era': 3.912023005428146,
 'pilih': 1.07880966137193,
 'ikn': 2.995732273553991,
 'juang': 2.120263536200091,
 'hal': 4.605170185988092,
 'tantang': 3.912023005428146,
 'wana': 4.605170185988092,
 'kelola': 2.302585092994046,
 'lima': 2.5257286443082556,
 'hubung': 1.7147984280919266,
 'makin': 2.8134107167600364,
 'tindak': 2.120263536200091,
 'sering': 2.995732273553991,
 'catat': 2.659260036932778,
 'juli': 2.659260036932778,
 'pusat': 1.1394342831883648,
 'nasional': 1.4696759700589417,
 'daerah': 1.2039728043259361,
 'sengaja': 3.912023005428146,
 'nilai': 1.6094379124341003,
 'khawatir': 2.995732273553991,
 'resentralisasi': 4.605170185988092,
 'berangus': 4.605170185988092,
 'khusus': 1.6607312068216509,
 'aman': 1.8971199848858813,
 'lsi': 3.912023005428146,
 'jelas': 1.171182981502945,
 'papar': 2.8134107167600364,
 'pimpin': 1.4696759700589417,
 'serius': 3.2188758248682006,
 'krisis': 3.506557897319982,
 'regresi': 4.605170185988092,
 'adil': 1.7719568419318754,
 'rayap': 4.605170185988092,
 'neodevelopmentalisme': 4.605170185988092,
 'persen': 2.207274913189721,
 'konservatif': 4.605170185988092,
 'sekarang': 2.120263536200091,
 'pesawat': 2.995732273553991,
 'mati': 2.995732273553991,
 'eksekutif': 3.2188758248682006,
 'takut': 3.2188758248682006,
 'lunak': 4.605170185988092,
 'mulai': 1.4271163556401458,
 'masa': 1.9661128563728327,
 'partisan': 4.605170185988092,
 'ooligopomedia': 4.605170185988092,
 'pandang': 3.2188758248682006,
 'taktik': 4.605170185988092,
 'perintah': 1.3470736479666094,
 'kuasa': 2.120263536200091,
 'kalau': 1.3470736479666094,
 'laku': 0.5798184952529422,
 'sipil': 2.995732273553991,
 'independensinya': 4.605170185988092,
 'kronologi': 3.2188758248682006,
 'racun': 3.506557897319982,
 'lawan': 2.5257286443082556,
 'kristiyanto': 3.2188758248682006,
 'frekuensi': 4.605170185988092,
 'terap': 2.8134107167600364,
 'international': 3.912023005428146,
 'kutip': 2.5257286443082556,
 'maharani': 3.912023005428146,
 'politik': 1.3862943611198906,
 'direktur': 2.5257286443082556,
 'survei': 2.659260036932778,
 'urus': 1.7719568419318754,
 'afganistan': 4.605170185988092,
 'transaksi': 4.605170185988092,
 'soekarnoputri': 3.2188758248682006,
 'gelintir': 4.605170185988092,
 'kelompok': 2.5257286443082556,
 'sentralisasi': 4.605170185988092,
 'pluralisme': 4.605170185988092,
 'geser': 3.912023005428146,
 'sikap': 2.5257286443082556,
 'amnesty': 4.605170185988092,
 'kait': 1.3862943611198906,
 'tempoco': 0.9162907318741551,
 'semua': 1.3093333199837622,
 'stasiun': 2.8134107167600364,
 'umum': 0.9416085398584451,
 'kunci': 3.506557897319982,
 'belah': 3.506557897319982,
 'baru': 1.2729656758128876,
 'pdip': 1.8971199848858813,
 'revisi': 3.2188758248682006,
 'pertama': 1.9661128563728327,
 'tangkap': 2.207274913189721,
 'akibat': 2.207274913189721,
 'ruuruu': 4.605170185988092,
 'hukum': 1.6607312068216509,
 'monopoli': 4.605170185988092,
 'bebas': 3.912023005428146,
 'adik': 3.506557897319982,
 'larang': 3.2188758248682006,
 'talib': 4.605170185988092,
 'kubu': 3.506557897319982,
 'ujar': 0.7339691750802005,
 'milu': 1.7719568419318754,
 'tuduh': 3.506557897319982,
 'skor': 4.605170185988092,
 'lini': 4.605170185988092,
 'turun': 2.302585092994046,
 'otonomi': 4.605170185988092,
 'lembaga': 2.120263536200091,
 'bukan': 1.3470736479666094,
 'enam': 3.912023005428146,
 'swasta': 3.912023005428146,
 'ambil': 2.0402208285265546,
 'masalah': 1.8325814637483102,
 'sebab': 2.8134107167600364,
 'puan': 3.912023005428146,
 'teknologi': 2.659260036932778,
 'indikator': 3.912023005428146,
 'merosot': 4.605170185988092,
 'enggan': 3.912023005428146,
 'oligopomedia': 4.605170185988092,
 'hampir': 2.995732273553991,
 'ite': 3.912023005428146,
 'musabab': 4.605170185988092,
 'contoh': 3.506557897319982,
 'orangorang': 2.8134107167600364,
 'undangundang': 3.2188758248682006,
 'guna': 1.7147984280919266,
 'anak': 1.7719568419318754,
 'macam': 3.2188758248682006,
 'kontrol': 3.506557897319982,
 'empat': 2.120263536200091,
 'usaha': 2.207274913189721,
 'publik': 2.120263536200091,
 'lewat': 2.0402208285265546,
 'muslim': 3.912023005428146,
 'kelompokkelompok': 4.605170185988092,
 'megawati': 2.659260036932778,
 'lingkung': 2.659260036932778,
 'represi': 4.605170185988092,
 'aktivis': 4.605170185988092,
 'otoritarianisme': 4.605170185988092,
 'cakup': 4.605170185988092,
 'orang': 0.8675005677047231,
 'agendaagenda': 4.605170185988092,
 'usman': 3.912023005428146,
 'dua': 1.4271163556401458,
 'politisasi': 3.912023005428146,
 'waris': 3.912023005428146,
 'informasi': 1.8971199848858813,
 'radikalisme': 4.605170185988092,
 'internasional': 3.2188758248682006,
 'ruang': 2.5257286443082556,
 'masyarakat': 1.2378743560016172,
 'pers': 2.659260036932778,
 'gemar': 4.605170185988092,
 'materi': 3.2188758248682006,
 'kurang': 2.302585092994046,
 'lebih': 0.7985076962177716,
 'ideologis': 4.605170185988092,
 'tajam': 3.506557897319982,
 'bunuh': 3.2188758248682006,
 'masuk': 1.171182981502945,
 'potensi': 2.659260036932778,
 'penting': 1.6094379124341003,
 'hamid': 4.605170185988092,
 'tiga': 1.7147984280919266,
 'hukumhukum': 4.605170185988092,
 'beber': 3.912023005428146,
 'kendali': 2.995732273553991,
 'polarisasi': 4.605170185988092,
 'ekonomi': 1.9661128563728327,
 'jppr': 4.605170185988092,
 'elektronik': 3.2188758248682006,
 'bahkan': 1.8971199848858813,
 'enggak': 2.0402208285265546,
 'label': 4.605170185988092,
 'lembagalembaga': 4.605170185988092,
 'konstitusi': 2.0402208285265546,
 'bisnis': 3.912023005428146,
 'investasi': 2.995732273553991,
 'acu': 3.506557897319982,
 'mahkamah': 2.120263536200091,
 'apa': 1.3470736479666094,
 'siber': 3.912023005428146,
 'ciut': 4.605170185988092,
 'militer': 2.8134107167600364,
 'partai': 1.0498221244986776,
 'tentara': 3.506557897319982,
 'curah': 3.912023005428146,
 'kamis': 1.6094379124341003,
 'imbang': 4.605170185988092,
 'akhir': 1.4696759700589417,
 'ratus': 3.506557897319982,
 'agung': 2.995732273553991,
 'agenda': 2.407945608651872,
 'ketua': 0.7985076962177716,
 'negara': 1.5141277326297755,
 'koersif': 4.605170185988092,
 'tni': 2.407945608651872,
 'didik': 2.207274913189721,
 'siar': 2.995732273553991,
 'media': 1.9661128563728327,
 'sah': 2.995732273553991,
 'butuh': 2.659260036932778,
 'tegak': 2.995732273553991,
 'beri': 0.9942522733438669,
 'ancam': 2.8134107167600364,
 'otoriter': 4.605170185988092,
 'dekade': 3.912023005428146,
 'demokrasi': 2.407945608651872,
 'jumlah': 0.843970070294529,
 'kembali': 3.912023005428146,
 'milik': 1.1394342831883648,
 'temu': 1.3093333199837622,
 'tuntas': 3.506557897319982,
 'nama': 1.5141277326297755,
 'kakak': 4.605170185988092,
 'kriminalisasi': 3.912023005428146,
 'represif': 4.605170185988092,
 'ham': 4.605170185988092,
 'data': 2.407945608651872,
 'papua': 2.659260036932778,
 'lemah': 4.605170185988092,
 'periode': 2.407945608651872,
 'tega': 3.912023005428146,
 'bungkam': 4.605170185988092,
 'rakyat': 1.8971199848858813,
 'kasus': 2.207274913189721,
 'adopsi': 3.912023005428146,
 'lapor': 1.6094379124341003,
 'lanjut': 0.9942522733438669,
 'bawah': 3.506557897319982,
 'memang': 1.8971199848858813,
 'jaring': 1.8971199848858813,
 'arsenik': 4.605170185988092,
 'oposisi': 4.605170185988092,
 'sorot': 2.659260036932778,
 'navigasi': 4.605170185988092,
 'kini': 2.207274913189721,
 'bentuk': 2.120263536200091,
 'saling': 3.506557897319982,
 'polri': 2.659260036932778,
 'konglomerat': 4.605170185988092,
 'hasto': 2.995732273553991,
 'orde': 4.605170185988092,
 'sosial': 1.8971199848858813,
 'pidana': 2.5257286443082556,
 'televisi': 3.506557897319982,
 'mungkin': 1.8971199848858813,
 'afirmatif': 4.605170185988092,
 'alatalat': 3.912023005428146,
 'hingga': 0.843970070294529,
 'munir': 4.605170185988092,
 'dapat': 0.9675840262617057,
 'kpk': 3.506557897319982,
 'keras': 1.9661128563728327,
 'cenderung': 3.912023005428146,
 'peran': 2.995732273553991,
 'banyak': 1.0498221244986776,
 'jaksa': 2.995732273553991,
 'tema': 3.506557897319982,
 'manfaat': 2.995732273553991,
 'tegalluar': 3.912023005428146,
 'jadwal': 2.407945608651872,
 'libur': 2.995732273553991,
 'selatan': 1.8971199848858813,
 'tiket': 3.506557897319982,
 'whoosh': 3.912023005428146,
 'rabu': 1.5606477482646683,
 'mampang': 4.605170185988092,
 'lokasi': 2.207274913189721,
 'naik': 2.207274913189721,
 'detikcom': 2.5257286443082556,
 'periksa': 1.9661128563728327,
 'cetak': 4.605170185988092,
 'luar': 2.207274913189721,
 'lalu': 0.8675005677047231,
 'tumpang': 3.2188758248682006,
 'kereta': 3.2188758248682006,
 'jalan': 0.9942522733438669,
 'panjang': 2.8134107167600364,
 'pekan': 3.2188758248682006,
 'pergi': 3.912023005428146,
 'satu': 0.843970070294529,
 'tahu': 1.3862943611198906,
 'kece': 3.912023005428146,
 'pukul': 1.5141277326297755,
 'lihat': 1.3862943611198906,
 'tugas': 1.6094379124341003,
 'ramai': 2.995732273553991,
 'berangkat': 2.5257286443082556,
 'prapatan': 4.605170185988092,
 'belanja': 2.995732273553991,
 'pemberitahuan': 3.506557897319982,
 'cepat': 2.302585092994046,
 'pantau': 2.120263536200091,
 'wib': 1.8971199848858813,
 'tuju': 1.8325814637483102,
 'malam': 1.9661128563728327,
 'gilir': 3.912023005428146,
 'tampak': 2.8134107167600364,
 'bandung': 2.8134107167600364,
 'beberapa': 1.2729656758128876,
 'suara': 1.6094379124341003,
 'sampai': 1.1394342831883648,
 'langsung': 1.3093333199837622,
 'waktu': 1.3093333199837622,
 'kawasan': 2.302585092994046,
 'lancar': 2.8134107167600364,
 'lantai': 3.912023005428146,
 'tunggu': 2.407945608651872,
 'halim': 3.2188758248682006,
 'tpstps': 4.605170185988092,
 'ikut': 1.2378743560016172,
 'layan': 2.207274913189721,
 'datang': 1.3470736479666094,
 'prosedur': 3.506557897319982,
 'dpk': 4.605170185988092,
 'ktp': 3.506557897319982,
 'apabila': 2.5257286443082556,
 'pasti': 1.4271163556401458,
 'jam': 2.5257286443082556,
 'masingmasing': 2.207274913189721,
 'mungut': 2.5257286443082556,
 'hak': 2.302585092994046,
 'klik': 4.605170185988092,
 'tutup': 2.407945608651872,
 'cekdptonlinekpugoid': 4.605170185988092,
 'baik': 0.9416085398584451,
 'kategori': 3.506557897319982,
 'kpps': 4.605170185988092,
 'pidato': 2.995732273553991,
 'kondisi': 2.302585092994046,
 'bilik': 4.605170185988092,
 'kpu': 1.7719568419318754,
 'selasa': 1.8325814637483102,
 'surat': 1.8325814637483102,
 'daftar': 1.7719568419318754,
 'selenggara': 2.120263536200091,
 'hasyim': 3.912023005428146,
 'mana': 2.120263536200091,
 'sebagimana': 4.605170185988092,
 'coblos': 4.605170185988092,
 'tetap': 1.6094379124341003,
 'nik': 4.605170185988092,
 'arah': 1.9661128563728327,
 'asyari': 3.912023005428146,
 'sesuai': 1.3470736479666094,
 'dpt': 3.912023005428146,
 'minta': 1.3093333199837622,
 'muncul': 2.0402208285265546,
 'tps': 3.912023005428146,
 'ada': 0.9942522733438669,
 'sebelumsebelumnya': 4.605170185988092,
 'cara': 2.995732273553991,
 'komisi': 1.7147984280919266,
 'alamat': 3.506557897319982,
 'sehat': 2.407945608651872,
 'tenaga': 3.912023005428146,
 'low': 4.605170185988092,
 'daring': 2.995732273553991,
 'tanah': 2.0402208285265546,
 'harap': 1.6607312068216509,
 'capai': 2.302585092994046,
 'usia': 2.659260036932778,
 'kuota': 3.912023005428146,
 'nada': 3.912023005428146,
 'launching': 4.605170185988092,
 'simpang': 3.506557897319982,
 'lansir': 2.5257286443082556,
 'dokter': 3.506557897319982,
 'gera': 2.8134107167600364,
 'latief': 4.605170185988092,
 'jemaah': 2.8134107167600364,
 'ali': 2.8134107167600364,
 'pulang': 2.8134107167600364,
 'sekretaris': 2.0402208285265546,
 'kang': 4.605170185988092,
 'laman': 2.995732273553991,
 'kemas': 3.912023005428146,
 'unjuk': 3.2188758248682006,
 'air': 2.207274913189721,
 'ramdhani': 4.605170185988092,
 'kemenag': 3.912023005428146,
 'usung': 1.9661128563728327,
 'dirjen': 3.912023005428146,
 'fakta': 3.506557897319982,
 'jamaah': 4.605170185988092,
 'tagline': 4.605170185988092,
 'bugar': 4.605170185988092,
 'jenis': 3.2188758248682006,
 'hilman': 4.605170185988092,
 'perdosri': 4.605170185988092,
 'luncur': 3.912023005428146,
 'tim': 1.7147984280919266,
 'himpun': 3.506557897319982,
 'menjelaskaan': 4.605170185988092,
 'haji': 2.8134107167600364,
 'atur': 2.120263536200091,
 'pakar': 2.8134107167600364,
 'luring': 4.605170185988092,
 'jaga': 2.207274913189721,
 'sapa': 2.8134107167600364,
 'jenderal': 2.120263536200091,
 'ribu': 2.8134107167600364,
 'fukum': 4.605170185988092,
 'pondok': 2.8134107167600364,
 'dhani': 4.605170185988092,
 'pansus': 3.2188758248682006,
 'tunai': 4.605170185988092,
 'ikhtiar': 4.605170185988092,
 'rangkai': 3.506557897319982,
 'bagi': 1.8971199848858813,
 'yaqut': 3.912023005428146,
 'wakil': 1.0498221244986776,
 'kerap': 3.506557897319982,
 'demikian': 3.912023005428146,
 'phu': 4.605170185988092,
 'saksi': 2.120263536200091,
 'giat': 3.2188758248682006,
 'impact': 4.605170185988092,
 'laksana': 1.5606477482646683,
 'susun': 3.2188758248682006,
 'duga': 1.7719568419318754,
 'bantah': 3.912023005428146,
 'faktor': 3.506557897319982,
 'qoumas': 3.912023005428146,
 'fisik': 3.2188758248682006,
 'cholil': 3.506557897319982,
 'perdokhi': 4.605170185988092,
 'mangkir': 3.912023005428146,
 'ibadah': 2.995732273553991,
 'rupa': 1.0216512475319812,
 'april': 1.8325814637483102,
 'lansia': 3.912023005428146,
 'kaji': 3.912023005428146,
 'asrama': 4.605170185988092,
 'mampu': 2.5257286443082556,
 'uras': 4.605170185988092,
 'rasa': 1.8971199848858813,
 'rehabilitasi': 4.605170185988092,
 'sekjen': 2.995732273553991,
 'wafat': 3.912023005428146,
 'spesialias': 4.605170185988092,
 'tutur': 1.5606477482646683,
 'aerobik': 4.605170185988092,
 'rumus': 4.605170185988092,
 'sejarah': 2.995732273553991,
 'menteri': 1.3862943611198906,
 'teliti': 3.506557897319982,
 'senam': 4.605170185988092,
 'sempurna': 3.912023005428146,
 'bekal': 3.506557897319982,
 'gede': 4.605170185988092,
 'ramah': 3.506557897319982,
 'ihwal': 3.506557897319982,
 'menag': 4.605170185988092,
 'pria': 2.302585092994046,
 'rumah': 1.6607312068216509,
 'meski': 1.6094379124341003,
 'dasar': 1.6094379124341003,
 'perhati': 2.8134107167600364,
 'ahad': 2.8134107167600364,
 'umrah': 3.506557897319982,
 'suci': 3.2188758248682006,
 'lhp': 4.605170185988092,
 'masif': 3.506557897319982,
 'tenang': 4.605170185988092,
 'phpu': 2.995732273553991,
 'hariyono': 4.605170185988092,
 'senin': 1.3093333199837622,
 'bahas': 1.9661128563728327,
 'mohon': 2.207274913189721,
 'badan': 2.120263536200091,
 'opsi': 3.912023005428146,
 'form': 4.605170185988092,
 'sumber': 2.407945608651872,
 'kembang': 2.5257286443082556,
 'totok': 4.605170185988092,
 'pra': 4.605170185988092,
 'awas': 2.5257286443082556,
 'pilpres': 1.8325814637483102,
 'hari': 1.1086626245216111,
 'struktur': 3.2188758248682006,
 'langgar': 2.659260036932778,
 'kesiap': 2.995732273553991,
 'temanteman': 3.506557897319982,
 'beda': 2.8134107167600364,
 'tahap': 2.207274913189721,
 'jelang': 2.120263536200091,
 'kampanye': 2.995732273553991,
 'rapat': 1.7147984280919266,
 'sistematis': 3.506557897319982,
 'pisah': 2.8134107167600364,
 'hendak': 2.8134107167600364,
 'legislatif': 2.995732273553991,
 'kumpul': 2.5257286443082556,
 'bahan': 2.995732273553991,
 'sifat': 2.995732273553991,
 'pileg': 2.995732273553991,
 'dalil': 3.506557897319982,
 'jajar': 2.5257286443082556,
 'bawaslu': 2.8134107167600364,
 'serta': 2.207274913189721,
 'imbau': 2.995732273553991,
 'maret': 2.0402208285265546,
 'tak': 1.171182981502945,
 'tsm': 3.912023005428146,
 'uji': 3.912023005428146,
 'anggap': 2.5257286443082556,
 'siap': 1.7147984280919266,
 'adu': 2.5257286443082556,
 'hasil': 1.3093333199837622,
 'selisih': 2.995732273553991,
 'kotak': 2.8134107167600364,
 'awal': 1.9661128563728327,
 'utama': 1.8325814637483102,
 'kosong': 2.5257286443082556,
 'soal': 1.5606477482646683,
 'anggota': 1.7147984280919266,
 'dwi': 3.912023005428146,
 'barat': 1.7719568419318754,
 'bandar': 4.605170185988092,
 'tangsel': 3.2188758248682006,
 'sodiq': 4.605170185988092,
 'saat': 3.912023005428146,
 'inisial': 2.8134107167600364,
 'narkoba': 3.506557897319982,
 'devoy': 4.605170185988092,
 'belum': 1.6094379124341003,
 'bareng': 3.506557897319982,
 'temantemannya': 3.506557897319982,
 'aktivitas': 4.605170185988092,
 'wartawan': 2.0402208285265546,
 'ucap': 1.3470736479666094,
 'tempat': 1.5141277326297755,
 'sasar': 3.912023005428146,
 'samid': 4.605170185988092,
 'polisi': 1.6094379124341003,
 'bambang': 3.912023005428146,
 'dpo': 4.605170185988092,
 'nih': 3.912023005428146,
 'sana': 2.659260036932778,
 'situ': 2.995732273553991,
 'sabtu': 1.2378743560016172,
 'barang': 3.2188758248682006,
 'alias': 2.302585092994046,
 'gang': 4.605170185988092,
 'make': 4.605170185988092,
 'tewas': 2.995732273553991,
 'askar': 4.605170185988092,
 'suruh': 3.506557897319982,
 'selesai': 2.302585092994046,
 'jual': 3.506557897319982,
 'depoy': 4.605170185988092,
 'pecah': 4.605170185988092,
 'gram': 4.605170185988092,
 'dkk': 4.605170185988092,
 'besar': 1.4271163556401458,
 'cengkareng': 4.605170185988092,
 'sangkut': 2.995732273553991,
 'pesta': 4.605170185988092,
 'kenal': 2.995732273553991,
 'kompol': 3.506557897319982,

In [9]:
def compute_tfidf(tf_dict, idf_dict):
    tfidf = {}

    for word in tf_dict:
        if word in idf_dict:
            tfidf[word] = tf_dict[word] * idf_dict[word]
        else:
            tfidf[word] = 0

    return tfidf

In [12]:
df['TF_IDF'] = df['tf'].apply(lambda tf: compute_tfidf(tf, idf))
df

,Judul,Content,tf,TF_IDF
0,jokowi kena pakai adat betawi sidang tahun akh...,jakarta kompascom presiden joko widodo pakai b...,"{'jakarta': 0.5, 'kompascom': 0.125, 'presiden...","{'jakarta': 0.1505525463919608, 'kompascom': 0..."
1,amnesty international kan indikator krisis dem...,tempoco jakarta amnesty international indonesi...,"{'tempoco': 0.06666666666666667, 'jakarta': 0....","{'tempoco': 0.06108604879161034, 'jakarta': 0...."
2,jelang long weekend stasiun kereta cepat halim...,stasiun kereta cepat whoosh halim jakarta timu...,"{'stasiun': 1.0, 'kereta': 0.8, 'cepat': 0.6, ...","{'stasiun': 2.8134107167600364, 'kereta': 2.57..."
3,kpu tegas pilih tak daftar dpt nyoblos begini ...,jakarta kompascom komisi pilih umum kpu pasti ...,"{'jakarta': 0.07692307692307693, 'kompascom': ...","{'jakarta': 0.023161930214147818, 'kompascom':..."
4,kemenag luncur gera senam haji jaga tahan fisi...,tempoco jakarta menteri agama kemenag luncur s...,"{'tempoco': 0.04, 'jakarta': 0.08, 'menteri': ...","{'tempoco': 0.03665162927496621, 'jakarta': 0...."
...,...,...,...,...
95,program prioritas kemendikbud guru guru gerak ...,tempoco riau bijak merdeka ajar episode jumlah...,"{'tempoco': 0.0625, 'riau': 0.125, 'bijak': 0....","{'tempoco': 0.057268170742134694, 'riau': 0.48..."
96,cerita korban tipu visa haji ilegal panas ding...,mek kompascom lukman bukan nama benar orang gu...,"{'mek': 0.42857142857142855, 'kompascom': 0.14...","{'mek': 1.9736443654234679, 'kompascom': 0.237..."
97,gerindra sebut reshuffle menkumham sinkronisas...,jakarta kompascom ketua hari partai gerindra s...,"{'jakarta': 0.6, 'kompascom': 0.2, 'ketua': 0....","{'jakarta': 0.18066305567035296, 'kompascom': ..."
98,lawrence wong lantik jadi singapura,lawrence wong lantik perdana menteri singapura...,"{'lawrence': 0.14285714285714285, 'wong': 1.0,...","{'lawrence': 0.6578814551411559, 'wong': 4.605..."
99,kpu jakarta gelar rapat pleno agustus bahas st...,kpu dki jakarta bakal gelar rapat pleno agustu...,"{'kpu': 0.8, 'dki': 0.6666666666666666, 'jakar...","{'kpu': 1.4175654735455003, 'dki': 1.605297072..."

In [13]:
import math

def cosine_similarity(vec1, vec2):
    # dot product (x . y)
    dot_product = 0
    for word in vec1:
        if word in vec2:
            dot_product += vec1[word] * vec2[word]

    # panjang vektor x
    norm1 = 0
    for value in vec1.values():
        norm1 += value * value
    norm1 = math.sqrt(norm1)

    # panjang vektor y
    norm2 = 0
    for value in vec2.values():
        norm2 += value * value
    norm2 = math.sqrt(norm2)

    # cosine similarity
    if norm1 == 0 or norm2 == 0:
        return 0

    return dot_product / (norm1 * norm2)

In [16]:
similarity_matrix = []

for i in range(len(df)):
    row = []
    for j in range(len(df)):
        sim = cosine_similarity(df['TF_IDF'][i], df['TF_IDF'][j])
        row.append(sim)
    similarity_matrix.append(row)

In [17]:
import pandas as pd

sim_df = pd.DataFrame(similarity_matrix)

In [18]:
sim_df.index = df['Judul']
sim_df.columns = df['Judul']

In [19]:
sim_df

Judul,jokowi kena pakai adat betawi sidang tahun akhir simbol terima kasih jakarta,amnesty international kan indikator krisis demokrasi indonesia,jelang long weekend stasiun kereta cepat halim ramai tumpang malam,kpu tegas pilih tak daftar dpt nyoblos begini mekanisme,kemenag luncur gera senam haji jaga tahan fisik jemaah,bawaslu minta jajar siap lhp hadap gugat sengketa milu,polisi ungkap aktivitas depoy bandar narkoba tewas toren,truk mogok lintas kereta serpong jalan krl ganggu,jalan buntu anies baswedan pilkada jakarta ikut likaliku jalan,warga sebut benda rupa jimat mayat sarung pamulang,...,pkb godok nama maju pilkada jawa timur bukan cak imin,diskon tiket whoosh spesial hut cek info,prabowo batal hadir tutup muktamar pkb cak imin masuk angin,gerindra usung sanujidita pilkada lebak,katakata akhir haniyeh pimpin pergi muncul,program prioritas kemendikbud guru guru gerak hingga pppk,cerita korban tipu visa haji ilegal panas dingin takut tangkap polisi,gerindra sebut reshuffle menkumham sinkronisasi perintah depan,lawrence wong lantik jadi singapura,kpu jakarta gelar rapat pleno agustus bahas status dharma pongrekun
Judul,,,,,,,,,,,,,,,,,,,,,
jokowi kena pakai adat betawi sidang tahun akhir simbol terima kasih jakarta,1.000000,0.023902,0.003675,0.014731,0.010138,0.009185,0.053414,0.001008,0.021046,0.026414,...,0.022441,0.002694,0.022824,0.010828,0.025836,0.019581,0.023556,0.024797,0.011823,0.004709
amnesty international kan indikator krisis demokrasi indonesia,0.023902,1.000000,0.015900,0.028264,0.014115,0.033812,0.012176,0.001869,0.054341,0.015398,...,0.020181,0.009231,0.021418,0.020018,0.032488,0.023068,0.030194,0.047909,0.017733,0.010712
jelang long weekend stasiun kereta cepat halim ramai tumpang malam,0.003675,0.015900,1.000000,0.014937,0.010197,0.005028,0.010769,0.019499,0.004300,0.024215,...,0.025350,0.204780,0.015433,0.004279,0.011617,0.017419,0.010542,0.029410,0.012386,0.018868
kpu tegas pilih tak daftar dpt nyoblos begini mekanisme,0.014731,0.028264,0.014937,1.000000,0.020014,0.067688,0.012906,0.000355,0.047072,0.017126,...,0.051328,0.007198,0.048904,0.006416,0.006619,0.019877,0.009416,0.023325,0.013823,0.065606
kemenag luncur gera senam haji jaga tahan fisik jemaah,0.010138,0.014115,0.010197,0.020014,1.000000,0.010502,0.012100,0.012863,0.010058,0.008981,...,0.003178,0.012568,0.031574,0.003464,0.013945,0.041331,0.159310,0.010406,0.006211,0.005395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
program prioritas kemendikbud guru guru gerak hingga pppk,0.019581,0.023068,0.017419,0.019877,0.041331,0.011133,0.016071,0.000499,0.007408,0.005871,...,0.012866,0.010910,0.020639,0.010185,0.028825,1.000000,0.054641,0.015927,0.012941,0.014712
cerita korban tipu visa haji ilegal panas dingin takut tangkap polisi,0.023556,0.030194,0.010542,0.009416,0.159310,0.012827,0.043768,0.014498,0.009315,0.040902,...,0.018530,0.015606,0.005412,0.004075,0.012730,0.054641,1.000000,0.010445,0.003347,0.004735
gerindra sebut reshuffle menkumham sinkronisasi perintah depan,0.024797,0.047909,0.029410,0.023325,0.010406,0.022878,0.005157,0.001633,0.091574,0.010832,...,0.023175,0.022292,0.054601,0.076040,0.017254,0.015927,0.010445,1.000000,0.030838,0.016983
lawrence wong lantik jadi singapura,0.011823,0.017733,0.012386,0.013823,0.006211,0.009621,0.005499,0.001366,0.006870,0.014395,...,0.007613,0.002319,0.022650,0.002894,0.023156,0.012941,0.003347,0.030838,1.000000,0.012708
kpu jakarta gelar rapat pleno agustus bahas status dharma pongrekun,0.004709,0.010712,0.018868,0.065606,0.005395,0.090851,0.008648,0.004622,0.092107,0.012382,...,0.064275,0.016485,0.027042,0.058042,0.016592,0.014712,0.004735,0.016983,0.012708,1.000000