In [1]:
import pandas as pd
import re
import string
import nltk
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to E:\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to E:\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
data = pd.read_csv("../../dataset/politik_merge.csv")
data

NameError: name 'pd' is not defined

In [1]:
df = data[['Judul','Content']].head(100)
df

NameError: name 'data' is not defined

In [6]:

stemmer_factory = StemmerFactory()
stemmer = stemmer_factory.create_stemmer()

stop_factory = StopWordRemoverFactory()
stop_words = set(stop_factory.get_stop_words())

In [7]:
def preprocess_text(text):
    if pd.isnull(text):
        return []

    text = text.lower()

    text = BeautifulSoup(text, "html.parser").get_text()

    text = re.sub(r'http\S+|www\S+', '', text)

    text = text.translate(str.maketrans('', '', string.punctuation))

    text = re.sub(r'\d+', '', text)

    text = re.sub(r'\s+', ' ', text).strip()

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in stop_words]

    tokens = [stemmer.stem(word) for word in tokens]

    return tokens

In [8]:
df['processed'] = df['Content'].apply(preprocess_text)

df

,Judul,Content,processed
0,Jokowi Kenakan Pakaian Adat Betawi di Sidang T...,"JAKARTA, KOMPAS.com - Presiden Joko Widodo me...","[jakarta, kompascom, presiden, joko, widodo, p..."
1,Amnesty International Beberkan 6 Indikator Kri...,"TEMPO.CO, Jakarta - Amnesty International Indo...","[tempoco, jakarta, amnesty, international, ind..."
2,"Jelang Long Weekend, Stasiun Kereta Cepat Hali...","Stasiun kereta cepat Whoosh di Halim, Jakarta ...","[stasiun, kereta, cepat, whoosh, halim, jakart..."
3,KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa...,"JAKARTA, KOMPAS.com - Komisi Pemilihan Umum (...","[jakarta, kompascom, komisi, pilih, umum, kpu,..."
4,Kemenag Luncurkan Gerakan Senam Haji Jaga Keta...,"TEMPO.CO, Jakarta - Kementerian Agama atau Kem...","[tempoco, jakarta, menteri, agama, kemenag, lu..."
...,...,...,...
95,Ini 5 Program Prioritas Kemendikbud untuk Guru...,"TEMPO.CO, Riau - Kebijakan Merdeka Belajar sa...","[tempoco, riau, bijak, merdeka, ajar, episode,..."
96,Cerita Korban Penipuan Visa Haji Ilegal: Panas...,"MEKKAH, KOMPAS.com- Lukman (bukan nama sebena...","[mek, kompascom, lukman, bukan, nama, benar, o..."
97,"Gerindra Sebut ""Reshuffle"" Menkumham untuk Sin...","JAKARTA, KOMPAS.com - Ketua Harian Partai Ger...","[jakarta, kompascom, ketua, hari, partai, geri..."
98,Lawrence Wong Dilantik Jadi PM Singapura,Lawrence Wong dilantik sebagai Perdana Menteri...,"[lawrence, wong, lantik, perdana, menteri, pm,..."
99,"KPU Jakarta Gelar Rapat Pleno 19 Agustus, Baha...",KPU DKI Jakarta bakal menggelar rapat pleno pa...,"[kpu, dki, jakarta, bakal, gelar, rapat, pleno..."

In [9]:
df['processed_text'] = df['processed'].apply(lambda x: " ".join(x))

df

,Judul,Content,processed,processed_text
0,Jokowi Kenakan Pakaian Adat Betawi di Sidang T...,"JAKARTA, KOMPAS.com - Presiden Joko Widodo me...","[jakarta, kompascom, presiden, joko, widodo, p...",jakarta kompascom presiden joko widodo pakai b...
1,Amnesty International Beberkan 6 Indikator Kri...,"TEMPO.CO, Jakarta - Amnesty International Indo...","[tempoco, jakarta, amnesty, international, ind...",tempoco jakarta amnesty international indonesi...
2,"Jelang Long Weekend, Stasiun Kereta Cepat Hali...","Stasiun kereta cepat Whoosh di Halim, Jakarta ...","[stasiun, kereta, cepat, whoosh, halim, jakart...",stasiun kereta cepat whoosh halim jakarta timu...
3,KPU Tegaskan Pemilih Tak Terdaftar di DPT Bisa...,"JAKARTA, KOMPAS.com - Komisi Pemilihan Umum (...","[jakarta, kompascom, komisi, pilih, umum, kpu,...",jakarta kompascom komisi pilih umum kpu ri pas...
4,Kemenag Luncurkan Gerakan Senam Haji Jaga Keta...,"TEMPO.CO, Jakarta - Kementerian Agama atau Kem...","[tempoco, jakarta, menteri, agama, kemenag, lu...",tempoco jakarta menteri agama kemenag luncur s...
...,...,...,...,...
95,Ini 5 Program Prioritas Kemendikbud untuk Guru...,"TEMPO.CO, Riau - Kebijakan Merdeka Belajar sa...","[tempoco, riau, bijak, merdeka, ajar, episode,...",tempoco riau bijak merdeka ajar episode jumlah...
96,Cerita Korban Penipuan Visa Haji Ilegal: Panas...,"MEKKAH, KOMPAS.com- Lukman (bukan nama sebena...","[mek, kompascom, lukman, bukan, nama, benar, o...",mek kompascom lukman bukan nama benar orang gu...
97,"Gerindra Sebut ""Reshuffle"" Menkumham untuk Sin...","JAKARTA, KOMPAS.com - Ketua Harian Partai Ger...","[jakarta, kompascom, ketua, hari, partai, geri...",jakarta kompascom ketua hari partai gerindra s...
98,Lawrence Wong Dilantik Jadi PM Singapura,Lawrence Wong dilantik sebagai Perdana Menteri...,"[lawrence, wong, lantik, perdana, menteri, pm,...",lawrence wong lantik perdana menteri pm singap...
99,"KPU Jakarta Gelar Rapat Pleno 19 Agustus, Baha...",KPU DKI Jakarta bakal menggelar rapat pleno pa...,"[kpu, dki, jakarta, bakal, gelar, rapat, pleno...",kpu dki jakarta bakal gelar rapat pleno agustu...

In [10]:
df.to_csv("../../dataset/news_preprocess.csv", index=False)

In [11]:
df['char_before'] = df['Content'].str.len()

df['char_after'] = df['processed_text'].str.len()

df['word_before'] = df['Content'].str.split().str.len()

df['word_after'] = df['processed_text'].str.split().str.len()

In [12]:
df[['char_before', 'char_after', 'word_before', 'word_after']]

    char_before  char_after  word_before  word_after
0          1677        1145          235         173
1          4906        3354          627         464
2           999         696          137         104
3          1141         681          157         107
4          2595        1754          373         274
..          ...         ...          ...         ...
95         2806        1853          383         279
96         1972        1336          280         205
97         1586        1123          201         156
98         1244         792          168         118
99         3546        2278          488         335

[100 rows x 4 columns]